### ISSUE TITLE
Not working with Aurelia CLI bundler

### ISSUE THREAD

**Issue by robinchesterman** [magnusdanielson/au-office-ui#3]
Hi,

I have used the Aurelia CLI to bootstrap an empty project, choosing the Aurelia bundler (with RequireJS) as opposed to Webpack, then installed this plugin.

When running the app, I get a problem that seems to originate from React's scheduler, whatever that is:

```
Uncaught ReferenceError: process is not defined
    at Object.<anonymous> (scheduler.development.js:14)
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.enable (require.js:1176)
    at Object.enable (require.js:1557)
    at Module.<anonymous> (require.js:1161)
    at require.js:134
    at each (require.js:59)
    at Module.enable (require.js:1113)
    at Object.enable (require.js:1557)
```

The line in question:

```

if (process.env.NODE_ENV !== "production") {
```

I don't really understand where or why this is getting called - this is in the vendor bundle, running in the browser, not a node environment.

**Comment by magnusdanielson** [comment]
I got it working. I am not sure if it is a hack or a solution, but anyway.

Add a file called nodeprocess.js at the root of your project. Same level as the node_modules folder.
Insert below content:

    var process = {} || process;
    process.browser = true;
    process.env =
    {
        NODE_ENV : 'production'
    }

Then add below to your aurelia.json file. It is just the line refering to nodeprocess.js you need to add.

    "name": "vendor-bundle.js",
        "prepend": [
          "nodeprocess.js",
          "node_modules/requirejs/require.js"
        ],

Now process is defined with enough attributes to get it running. I don't know if it has any other side effects. This assumes that you want to run in the browser and you are using CLI for bundling with RequireJS.

P.S. Glad to hear you are using au-office-ui

**Comment by magnusdanielson** [comment]
Can we close this now?

**Comment by magnusdanielson** [comment]
Closing as resolved
