### ISSUE TITLE
any plans to support the new fluent-ui?

### ISSUE THREAD

**Issue by mitchcapper** [magnusdanielson/au-office-ui#4]
Microsoft has moved from the office-ui to the fairly similar fluent-ui for going forward:
https://developer.microsoft.com/en-us/fluentui#/

As not many au compat ui options out there this one is quite nice!

**Comment by magnusdanielson** [comment]
Sure, I will fix it! I will create a new npm package for au-fluentui.

**Comment by mitchcapper** [comment]
Fantastic! Thank you.

**Comment by magnusdanielson** [comment]
New repo here https://github.com/magnusdanielson/au-fluent-ui
Npm package here https://www.npmjs.com/package/@dunite/au-fluent-ui

I have sucessfully created a new project with
`au new`
Then added
`au install @dunite/au-fluent-ui`
And then added peer dependencies.

package.json looks like this

    "dependencies": {
    "@dunite/au-fluent-ui": "^0.1.3",
    "@types/react": "^16.8.25",
    "@types/react-dom": "^16.8.4",
    "aurelia-animator-css": "^1.0.4",
    "aurelia-bootstrapper": "^2.3.3",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
After that all controls work. Check out the demo site https://magnusdanielson.github.io/au-fluent-ui/

If you have time to test I will close this issue and bump to 1.0.0 version
